accounts/urls.py
from django.urls import path

from accounts.views import LoginAuthView, LogoutAuthView, SignUpAuthView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginAuthView.as_view(), name="login"),
    path("logout/", LogoutAuthView.as_view(), name="logout"),
    path("signup/", SignUpAuthView.as_view(), name="signup"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("website.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path

from website.views import WebsiteListView, WebsiteDetailView, WebsiteCreateView, WebsiteUpdateView


app_name = "website"

urlpatterns = [
    path("create/", WebsiteCreateView.as_view(), name="create"),
    path("<uuid:pk>/edit", WebsiteUpdateView.as_view(), name="update"),
    path("<uuid:pk>/", WebsiteDetailView.as_view(), name="detail"),
    path("", WebsiteListView.as_view(), name="list"),
]

accounts/models.py
from django.db import models

# Create your models here.

core/additional/models.py
from uuid import uuid4

from django.db import models


class CoreModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True

users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

website/models.py
from functools import reduce
import itertools
import operator

from django.db import models
from django.db.models import Q
from django.urls import reverse

from core.additional.models import CoreModel


class WebsiteQuerySet(models.QuerySet):

    def actives(self):
        return self.filter(is_active=True)

    def in_actives(self):
        return self.filter(is_active=False)

    def search(self, query):
        query_split = [i.split(",") for i in query.split(" ")]
        query_list = list(itertools.chain.from_iterable(query_split))
        query_filtered_list = [i for i in query_list if i != ""]
        lookup = reduce(operator.or_, (Q(is_active=True) & Q(title__icontains=option) for option in query_filtered_list))
        return self.filter(lookup)


class WebsiteManager(models.Manager):

    def get_queryset(self):
        return WebsiteQuerySet(self.model, using=self._db)

    def actives(self):
        return self.get_queryset().actives()

    def in_actives(self):
        return self.get_queryset().in_actives()

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().search(query)


class Website(CoreModel):
    title = models.CharField(max_length=128)
    url = models.URLField()

    objects = WebsiteManager()

    class Meta:
        verbose_name = "WEBサイト"
        verbose_name_plural = "WEBサイト"
        ordering = ("-timestamp", )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("website:detail", kwargs={"pk": self.pk})


class SnapQueryset(models.QuerySet):

    def actives(self):
        return self.filter(is_active=True)

    def in_actives(self):
        return self.filter(is_active=False)


class SnapManager(models.Manager):

    def get_queryset(self):
        return SnapQueryset(self.model, using=self._db)

    def actives(self):
        return self.get_queryset().actives()

    def in_actives(self):
        return self.get_queryset().in_actives()


def upload_image_to(instance, filename):
    asset_path = f"{str(instance.website.title)}/{filename}"
    return asset_path


class Snap(CoreModel):
    website = models.ForeignKey(Website, on_delete=models.CASCADE, related_name="snaps")
    snap = models.ImageField(upload_to=upload_image_to)

    objects = SnapManager()

    class Meta:
        verbose_name = "スナップショット"
        verbose_name_plural = "スナップショット"

    def __str__(self):
        return self.get_filename()

    def get_filename(self):
        return self.snap.name.split("/")[-1]

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm


class CustomAuthenticationForm(AuthenticationForm):
    pass

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


User = get_user_model()


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email", "username", )


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ("email", "username", )

website/forms.py
from django import forms

from website.models import Website, Snap


class WebsiteForm(forms.ModelForm):

    class Meta:
        model = Website
        fields = ("title", "url", )


SnapFormset = forms.inlineformset_factory(Website, Snap, fields=("snap",), can_delete=True, extra=1)

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.views import View
from django.views.generic import CreateView
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect

from accounts.forms import CustomAuthenticationForm
from users.forms import CustomUserCreationForm


class LoginAuthView(LoginView):
    form_class = CustomAuthenticationForm
    template_name: str = "accounts/login.html"


class LogoutAuthView(View):

    def post(self, request):
        logout(request)
        url = reverse("website:list")
        return redirect(url)


class SignUpAuthView(CreateView):
    form_class = CustomUserCreationForm
    template_name: str = "accounts/signup.html"
    success_url = reverse_lazy("website:list")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return redirect(self.get_success_url())

website/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from website.forms import WebsiteForm, SnapFormset
from website.models import Website


class WebsiteListView(ListView):
    context_object_name = "websites"
    template_name = "website/list.html"

    def get_queryset(self):
        queryset = Website.objects.actives()
        return queryset


class WebsiteDetailView(DetailView):
    model = Website
    template_name = "website/detail.html"


class WebsiteCreateView(LoginRequiredMixin, CreateView):
    model = Website
    template_name: str = "website/create.html"
    form_class = WebsiteForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["formset"] = SnapFormset(self.request.POST or None, files=self.request.FILES or None)
        return context

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        formset = context["formset"]
        if formset.is_valid():
            response = super().form_valid(form)
            formset.instance = self.object
            formset.save()
            return response
        else:
            return super().form_invalid(form)


class WebsiteUpdateView(LoginRequiredMixin, UpdateView):
    model = Website
    template_name: str = "website/edit.html"
    form_class = WebsiteForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["formset"] = SnapFormset(self.request.POST or None, files=self.request.FILES or None, instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        formset = context["formset"]
        if formset.is_valid():
            response = super().form_valid(form)
            formset.instance = self.object
            formset.save()
            return response
        else:
            return super().form_invalid(form)

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Cloudinary PythonAnywhere</title>
    <link href="https://cdn.jsdelivr.net/npm/beercss@2.2.11/dist/cdn/beer.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% block styles %}{% endblock styles %}
</head>

<body>
    {% include "widgets/navbar.html" %}
    <main class="responsive">
        {% block content %}{% endblock content %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/beercss@2.2.11/dist/cdn/beer.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/material-dynamic-colors@0.0.10/dist/cdn/material-dynamic-colors.min.js"
        type="text/javascript"></script>
    <script src="{% static 'js/index.js' %}"></script>
    {% block js %}{% endblock js %}
</body>

</html>

templates/accounts/login.html
{% extends '_base.html' %}
{% load widget_tweaks %}

{% block styles %}{% endblock styles %}

{% block content %}
{% include "widgets/back_to_list_button.html" %}
<div class="container">
    <h4>ログイン</h4>
    {% include "accounts/widgets/auth_form.html" %}
</div>
{% endblock content %}

{% block js %}{% endblock js %}

templates/accounts/logout_modal.html
<button class="small" data-ui="#logout-modal">ログアウト</button>

<div class="modal" id="logout-modal" style="z-index: 999;">
    <h5>本当にログアウトしますか？</h5>
    <div>OKを押すとログアウトします。</div>
    <nav class="right-align">
        <form action="{% url 'accounts:logout' %}" method="post" id="logout_submit_modal">
            {% csrf_token %}
            <button data-ui="#logout-modal" type="submit">OK</button>
        </form>
        <button class="border" data-ui="#logout-modal">キャンセル</button>
    </nav>
</div>

templates/accounts/signup.html
{% extends '_base.html' %}
{% load widget_tweaks %}

{% block styles %}{% endblock styles %}

{% block content %}
{% include "widgets/back_to_list_button.html" %}
<div class="container">
    <h4>ユーザー作成</h4>
    {% include "accounts/widgets/auth_form.html" %}
</div>
{% endblock content %}

{% block js %}{% endblock js %}

templates/accounts/widgets/auth_form.html
{% load widget_tweaks %}

<form action="." method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="field label border {% if field.errors %}invalid{% endif %}">
        <label for="{{field.id_for_label}}">{{ field.label }}</label>
        {{ field }}
        {% include "widgets/field_error.html" with field=field %}
    </div>
    {% endfor %}
    <div>
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
</form>

templates/website/create.html
{% extends '_base.html' %}
{% load static %}

{% block styles %}{% endblock styles %}

{% block content %}
{% include "widgets/back_to_list_button.html" %}
{% include "website/widgets/form.html" %}
{% endblock content %}

{% block js %}
<script src="{% static 'js/website/form.js' %}"></script>
{% endblock js %}

templates/website/detail.html
{% extends '_base.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/website/detail.css' %}">
{% endblock styles %}

{% block content %}
<div>
    {% include "widgets/back_to_list_button.html" %}
    <div class="container">
        <h4>{{ object.title }}</h4>
        <a href="{{ object.url }}" target="_blank" rel="noopener noreferrer">Open Url</a>

        {% if object.snaps.all|length > 0 %}
        <nav id="snaps" class="row scroll">
            {% for snap in website.snaps.all %}
            {% if snap.snap %}
            <img src="{{ snap.snap.url }}" alt="{{ snap.snap.name }}">
            {% endif %}
            {% endfor %}
        </nav>
        {% endif %}
    </div>

    {% if user.is_authenticated %}
    <a class="small chip primary" href="{% url 'website:update' pk=object.pk %}">Edit</a>
    {% endif %}
</div>
{% endblock content %}

{% block js %}{% endblock js %}

templates/website/edit.html
{% extends '_base.html' %}
{% load static %}

{% block styles %}{% endblock styles %}

{% block content %}
{% include "widgets/back_to_list_button.html" %}
{% include "website/widgets/form.html" %}
{% endblock content %}

{% block js %}
<script src="{% static 'js/website/form.js' %}"></script>
{% endblock js %}

templates/website/list.html
{% extends '_base.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/website/list.css' %}">
{% endblock styles %}

{% block content %}
<div>
    {% for website in websites %}
    <div class="list-cell">
        {% include "website/widgets/list_tile.html" with website=website %}
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/website/widgets/form.html
{% load widget_tweaks %}

<form action="" method="post" enctype="multipart/form-data" id="form-container">
    {% if form.errors %}
    {% for error in form.errors %}
    <article class="red5 white-text">
        <p>{{ error }}</p>
    </article>
    {% endfor %}
    {% endif %}
    {% csrf_token %}
    <div class="container">
        {% for field in form %}
        <div class="field label border {% if field.errors %}invalid{% endif %}">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% include "widgets/field_error.html" with field=field %}
        </div>
        {% endfor %}

        {{ formset.management_form }}
        <div id="snap-form-list">
            {% for snap_form in formset %}
            {% include "website/widgets/snap_form.html" with form=snap_form %}
            {% endfor %}
        </div>
    </div>

    <div>
        <button class="btn btn-primary" type="submit">送信</button>
        <button id="add-snap" class="btn" type="button">画像を追加</button>
    </div>
</form>

templates/website/widgets/list_tile.html
<article class="border mb-1">
    <h5>{{ website.title }}</h5>
    <p>{{ website.url }}</p>
    <nav>
        <a class="small chip primary" href="{{ website.get_absolute_url }}">Open Detail</a>
        <a class="small chip" href="{{ website.url }}" target="_blank" rel="noopener noreferrer">Open Url</a>
    </nav>
</article>
<div class="space"></div>

templates/website/widgets/snap_form.html
<div class="snap-form">
    {% for field in form.hidden_fields %}
    {{ field }}
    {% endfor %}
    <div class="grid">
        <div class="s6">
            <div class="field label border prefix suffix small">
                <i>attach_file</i>
                <label for="{{ form.snap.id_for_label }}">{{ form.snap.label }}</label>
                <input type="text">
                <input type="file" name="{{ form.snap.html_name }}" id="{{ form.snap.id_for_label }}">
                {% if form.instance.snap %}
                <img class="rounded" src="{{ form.instance.snap.url }}">
                {% endif %}
            </div>
        </div>
        <div class="s2">
            {% if form.instance.pk and form.instance.snap %}
            <label class="form-checkbox" for="{{ form.DELETE.id_for_label }}">
                <input type="checkbox" id="{{ form.DELETE.id_for_label }}" name="{{form.DELETE.html_name}}">
                {{form.DELETE.label}}
            </label>
            {% endif %}
        </div>
    </div>
</div>

templates/widgets/back_to_list_button.html
<a class="chip small primary" href="{% url 'website:list' %}">
    <i class="small">arrow_back</i>
    <span>Back</span>
</a>

templates/widgets/field_error.html
{% if field.errors %}
{% for error in field.errors %}
<span class="error">{{ error }}</span>
{% endfor %}
{% endif %}

templates/widgets/navbar.html
<header class="surface-variant">
    <nav>
        <h5 class="max">
            <a href="{% url "website:list" %}">Django + Cloudinary + PythonAnywhere</a>
        </h5>
        {% if user.is_authenticated %}
        <span>{{ user.username }}</span>
        <a class="small chip primary" href="{% url 'website:create' %}">
            作成
        </a>
        {% include "accounts/logout_modal.html" %}
        {% else %}
        <a class="small chip primary" href="{% url 'accounts:signup' %}">
            アカウント作成
        </a>
        <a class="small chip primary" href="{% url 'accounts:login' %}">
            ログイン
        </a>
        {% endif %}
    </nav>
</header>